# Generated by Django 4.1.5 on 2023-02-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is Sample Product'),
        ),
    ]
