# Generated by Django 4.1.7 on 2023-03-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_checkout_date_checkoutproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutProducts',
            new_name='CheckoutProduct',
        ),
    ]
